commands_to_run:
  steps:
    - name: "Starting scan for Liman MYS-fiber-render-engine (with Go)"
      command: echo "Starting scan for Liman MYS/core (with Go)"
      stepno: 1
      
    - name: "Secret Scan with Detect Secrets"
      command: "detect-secrets -C ${scan_directory} scan > ${output_file}"
      parameters:
        scan_directory: "../Desktop/Liman_MYS/fiber-render-engine"
        output_file: "../Desktop/Liman_MYS/results_fiber/secrets.json"
      post_command: "echo Detect Secrets complete. Results stored in ${output_directory}"
      post_parameters:
        output_directory: "../Desktop/Liman_MYS/results_fiber"
      stepno: 2

    - name: "Secret Scan with GitLeaks"
      command: docker run -v ${path_to_host_folder_to_scan}:/path -v ${output_path}:/output_path zricethezav/gitleaks:latest ${run_command_option} --source="/path" --report-format=json --report-path=/output_path/gitleaks_report.json
      parameters:
        path_to_host_folder_to_scan: "/home/aseren/Desktop/Liman_MYS/fiber-render-engine"
        run_command_option: detect
        output_path: "/home/aseren/Desktop/Liman_MYS/results_fiber"
      post_command: echo GitLeaks complete. Results stored in ${output_path}"
      stepno: 3
    
    - name: "Vulnerability Scan with Gosec"
      command: gosec -fmt=${output_type} -out=${output_path} ${scan_directory}/...
      parameters:
        scan_directory: ../Desktop/Liman_MYS/fiber-render-engine
        output_type: "json"
        output_path: "../Desktop/Liman_MYS/results_fiber/gosec.json"
      post_command: echo Gosec complete. Results stored in ${output_path}"
      stepno: 4

    - name: "Vulnerability Scan with Grype"
      command: "grype dir:${scan_directory} -o json --file ${output_path}"
      parameters:
        scan_directory: "../Desktop/Liman_MYS/fiber-render-engine"
        output_type: "json"
        output_path: "../Desktop/Liman_MYS/results_fiber/grype.json"
      post_command: "echo Grype scan Complete. Results stored in ${output_path}"
      post_parameters:
        output_path: "../Desktop/Liman_MYS/results_fiber/"
      stepno: 5
    
    - name: "Dependency Scan with OWASP Dependency Check"
      command: "dependency-check/bin/dependency-check.sh --scan \"${scan_directory}\" --out ${output_path}"
      parameters:
        scan_directory: "../Desktop/Liman_MYS/fiber-render-engine"
        output_path: "../Desktop/Liman_MYS/results_fiber"
      post_command: "echo OWASP Dependency Check Complete. Results stored in ${output_path}"
      post_parameters:
        output_path: "../Desktop/Liman_MYS/results_fiber"
      stepno: 6

    - name: "SBOM Generation With Syft"
      command: syft ${scan_directory} --output cyclonedx-json >> ${output_path}/sbom.json
      parameters:
        scan_directory: "../Desktop/Liman_MYS/fiber-render-engine"
        output_path: "../Desktop/Liman_MYS/results_fiber"
      post_command: "echo Syft Scan Complete. Results stored in ${output_path}"
      stepno: 7

    - name: "SBOM Scan with Grype"
      command: "grype sbom:${scan_path} -o json --file ${output_path}"
      parameters:
        scan_path: "../Desktop/Liman_MYS/results_fiber/sbom.json"
        output_type: "json"
        output_path: "../Desktop/Liman_MYS/results_fiber/grype_sbom_scan.json"
      post_command: "echo Grype scan Complete. Results stored in ${output_path}"
      post_parameters:
        output_path: "../Desktop/Liman_MYS/results_fiber/grype_sbom_scan.json"
      stepno: 8

    - name: "SAST Scan with SonarQube"
      command: >
        docker run
        --rm
        --network=host
        -e SONAR_HOST_URL="http://localhost:9000"
        -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=fiber"
        -e SONAR_TOKEN="sqp_ad552439041ee41df3dda5217c77d2b880268dc6"
        -v "/home/aseren/Desktop/Liman_MYS/fiber-render-engine:/usr/src"
        sonarsource/sonar-scanner-cli
      stepno: 9