commands_to_run:
  steps:
    - name: "Dependencytrack Deploy"
      command: "bash ./docker/destroy_depency_track.sh"
      stepno: 1
      post_command: "echo Dependencytrack has been finished"


    - name: "Finished"
      command: "echo DevSecOps Builder has been finished ${echo_text}"
      parameters:
        echo_text: "All Docker services destroyed."
      stepno: 2
