commands_to_run:
  steps:
    - name: "Start"
      command: echo "Welcome to DevSecOpsBuilder"
      stepno: 1
      
    - name: "List files"
      command: ls -l
      stepno: 2

    - name: "Get current directory"
      command: pwd
      stepno: 2

    - name: "GITLEAK-JOB"
      command: docker run -v ${path_to_host_folder_to_scan}:/path zricethezav/gitleaks:latest ${run_command_option} --source="/path" --verbose --report-format=json --report-path=/path/gitleaks_report.json
      parameters:
        path_to_host_folder_to_scan: "./lab/SecretsTest/"
        run_command_option: detect
        output_path: "./outputs/git-secrets/"
      post_command: mv ./lab/SecretsTest/gitleaks_report.json ${output_path}
      post_parameters:
        output_path: "./command_outputs/git-secrets/"
      stepno: 3


    - name: "TRUFFLEHOG-JOB"
      command: trufflehog git file://${git_repository_path} ${options}
      parameters:
        git_repository_path: "./lab/SecretsTest/"
        options: "--json >> ./lab/SecretsTest/trufflehog_result.json"
      post_command: mv ./lab/SecretsTest/trufflehog_result.json ${output_path}
      post_parameters:
        output_path: "./command_outputs/git-secrets/"
      stepno: 4
    
    - name: "DETECT-SECRETS-SCAN"
      command: detect-secrets scan ${scan_directory} >> ${output_path}/detect-secrets-results.json
      parameters:
        scan_directory: "./lab/SecretsTest/"
        output_path: "./command_outputs/git-secrets/"
      post_command: "echo Scan Complete. Results stored in ${output_path}"
      stepno: 5
    
    # You need to run ggsheild auth login
    #- name: "GGSHIELD-SCAN"
    #  command: ggshield secret scan repo ${scan_directory} >> ${output_path}/ggshield-results.txt
    #  parameters:
    #    scan_directory: "./lab/SecretsTest/"
    #    output_path: "./command_outputs/ggshield/"
    #  post_command: "echo GGShield Scan Complete. Results stored in ${output_path}"
    #  stepno: 6

    - name: "Finished"
      command: "echo DevSecOps Builder has been finished ${echo_text}"
      parameters:
        echo_text: "This is a test echo."
      stepno: 7
