commands_to_run:
  steps:
    - name: "Start"
      command: echo "Welcome to DevSecOpsBuilder"
      stepno: 1
      
    - name: "List files"
      command: ls -l
      stepno: 2

    - name: "Get current directory"
      command: pwd
      stepno: 2

    - name: "GITLEAK-JOB"
      command: docker run -v ${path_to_host_folder_to_scan}:/path zricethezav/gitleaks:latest ${run_command_option} --source="/path" ${options}
      parameters:
        path_to_host_folder_to_scan: "./lab/SecretsTest/"
        run_command_option: detect
        options: --verbose --report-format=json --report-path=${path_to_host_folder_to_scan}/gitleaks_report.json 
        output_path: "./outputs/git-secrets/"
      post_command: mv ${path_to_host_folder_to_scan}gitleaks_report.json ${output_path}
      stepno: 3

    - name: "TRUFFLEHOG-JOB"
      command: trufflehog git file://${git_repository_path} ${options}
      parameters:
        git_repository_path: "./lab/SecretsTest/"
        options: "--json >> ./lab/SecretsTest//trufflehog_result.json"
      post_command: mv ./lab/SecretsTest//trufflehog_report.json ${output_path}
      output_path: "./outputs/git-secrets/"
      stepno: 4


    - name: "Finished"
      command: "echo DevSecOps Builder has been finished ${echo_text}"
      parameters:
        echo_text: "This is a test echo."
      stepno: 5
