commands_to_run:
  steps:
    - name: "Starting scan for Python"
      command: echo "Starting scan with Python tools"
      stepno: 1
      
    - name: "Secret Scan with Detect Secrets"
      command: "detect-secrets -C ${scan_directory} scan > ${output_file}"
      parameters:
        scan_directory: "/lab/DVSA"
        output_file: "./command_outputs/python-scan/secrets.json"
      post_command: "echo Detect Secrets complete. Results stored in ${output_file}"
      post_parameters:
        output_file: "./command_outputs/python-scan/secrets.json"
      stepno: 2

    - name: "Bandit Scan"
      command: "bandit -r ${scan_directory} -f ${output_type} -o ${output_path}/bandit_result.json"
      parameters:
        scan_directory: "./lab/DVSA"
        output_type: "json"
        output_path: "./command_outputs/python-scan"
      post_command: "echo Bandit Scan Complete. Results stored in ${output_path}"
      post_parameters:
        output_path: "./command_outputs/python-scan/"
      stepno: 3

    - name: "Vulnerability Scan with Grype"
      command: "grype dir:${scan_directory} -o json --file ${output_path}"
      parameters:
        scan_directory: "./lab/DVSA"
        output_type: "json"
        output_path: "./command_outputs/python-scan/grype.json"
      post_command: "echo Grype scan Complete. Results stored in ${output_path}"
      post_parameters:
        output_path: "./command_outputs/python-scan/"
      stepno: 4

    - name: "Dependency Scan with Safety"
      command: "safety check --save-json ${output_path}"
      parameters:
        output_path: "./command_outputs/python-scan/"
      post_command: "echo Safety dependency scan Complete. Results stored in ${output_path}"
      post_parameters:
        output_path: "./command_outputs/python-scan/"
      stepno: 5

    

