commands_to_run:
  steps:
    - name: "PWD"
      command: "echo DevSecOps Builder has been started ${echo_text}"
      parameters:
        echo_text: "Scanner YAML"
      stepno: 1


    - name: "Grype Scanner Git Repo"
      command: "grype ${lab_path} -o ${output_type} >> ${output_path}"
      parameters:
        lab_path: "./lab/NodeGoat/"
        output_type: "json"
        output_path: "command_outputs/scanner/grype-repo-scan.json"
      stepno: 2
          

    - name: "Grype Scanner Docker Container"
      command: "grype ${docker_path} -o ${output_type} >> ${output_path}"
      parameters:
        docker_path: "zricethezav/gitleaks:latest"
        output_type: "json"
        output_path: "command_outputs/scanner/grype-gitleaks-docker-scan.json"
      stepno: 3
      

    - name: "Grype Scanner SBOM Scan"
      command: "syft ${repo_path} -o ${output_type} > vulnado-sbom.json >> ${sbom_path}"
      parameters:
        repo_path: "./lab/NodeGoat/"
        output_type: "syft-json"
        sbom_path: "command_outputs/scanner/syft-sbom.json"
      stepno: 4
      post_command: "grype ${sbom_path} -o ${output_type} >> ${output_path}"
      post_parameters:
        sbom_path: "command_outputs/scanner/syft-sbom.json"
        output_type: "json"
        output_path: "command_outputs/scanner/grype-sbom-scan.json"
    
    # Run **semgrep login** before running this playbook 
    #- name: "SEMGREP Deploy"
    #  command: " semgrep login && cd ${lab_path} && semgrep ${semgrep_config}"
    #  paremeters:
    #    lab_path: "./lab/WebGoat/"
    #    semgrep_config: "--config=p/r2c-ci --exclude=**/node_modules/** > >> ../../command_outputs/scanner/semgrep-log.txt"
    #  stepno: 5
    #  post_command: "echo semgrep has been finished"

    - name: "Finished"
      command: "echo DevSecOps Builder has been finished ${echo_text}"
      parameters:
        echo_text: "Scanners has been finished."
      stepno: 5
